### ISSUE TITLE
Not working on different trackers?

### ISSUE THREAD

**Issue by octophetus** [sbussetti/deluge-siphon#57] opened 2017-08-02 15:35 UTC
I'm no expert at this stuff but it is not working on several trackers and I'm not sure why.
Does not work in the following trackers:
**Apollo:**  First states "adding torrent" then displays an error stating that "There was an error. Torrent was not added." Yet I am able to copy the same link and then add by link in Deluge just fine.

**MyAnonaMouse:** Can right click and then select "add" just fine but When I left click it just downloads through browser the .torrent file.

**Sceneaccess.eu:** First states "adding torrent" then displays an error stating that "There was an error. Torrent was not added." Yet I am able to copy the same link and then add by link in Deluge just fine.

**Horror Charnel:** On right clicking to "add" it states that the torrent already is added when it is not.  When I left click it just downloads through browser the .torrent file. When I copy the link and try to add manually in Deluge, Deluge gives the error "Invalid file: not a valid bencoded string".  So, the only way to do it is to download the .torrent file and then manually add it to deluge.

Below are the results from Horror Charnel:

controller_actions.js:16 *** new DelugeConnection ***
controller_actions.js:312 _getSession invalid Objecterror: nullid: "-16990"result: false__proto__: Object
(anonymous) @ controller_actions.js:312
controller_actions.js:327 _doLogin__callback true
controller_actions.js:350 _checkDaemonConnection Object
controller_actions.js:391 _getDaemons__callback Object
controller_actions.js:406 _getHostStatus f12e372e1fd01d27a0537f09ca9aed046f7c170f
controller_actions.js:437 _getHostStatus__callback Object
controller_actions.js:472 _getConnectedDaemon__callback Connected Object
controller_actions.js:636 _getServerConfig Object
controller_actions.js:653 _getServerConfig__callback Object
controller_actions.js:309 _getSession valid Object
controller_actions.js:350 _checkDaemonConnection Object
controller_actions.js:364 _checkDaemonConnection__callback Object Object
controller_actions.js:636 _getServerConfig Object
controller_actions.js:653 _getServerConfig__callback Object
controller_actions.js:679 _getPlugins__callback Object
controller_actions.js:704 _getLabelInfo__callback Object
controller_actions.js:309 _getSession valid Object
controller_actions.js:350 _checkDaemonConnection Object
controller_actions.js:364 _checkDaemonConnection__callback Object Object
controller_actions.js:636 _getServerConfig Object
controller_actions.js:653 _getServerConfig__callback Object
controller_actions.js:270 _getDomainCookies for horrorcharnel.org
controller_actions.js:291 _getDomainCookies__callback horrorcharnel.org uid=7574;pass=d6123ffa07e90a31e5442d1ca73570cc;hashv=b94cbcbb740428a8d1d4b621a56d578d
controller_actions.js:912 _addTorrentUrlToServer core.add_torrent_url Array(3)
controller_actions.js:920 _addTorrentUrlToServer__callback Object
controller_actions.js:309 _getSession valid Object
controller_actions.js:350 _checkDaemonConnection Object
controller_actions.js:364 _checkDaemonConnection__callback Object Object
controller_actions.js:636 _getServerConfig Object
controller_actions.js:653 _getServerConfig__callback Object
controller_actions.js:270 _getDomainCookies for horrorcharnel.org
controller_actions.js:291 _getDomainCookies__callback horrorcharnel.org uid=7574;pass=d6123ffa07e90a31e5442d1ca73570cc;hashv=b94cbcbb740428a8d1d4b621a56d578d
controller_actions.js:912 _addTorrentUrlToServer core.add_torrent_url Array(3)
controller_actions.js:920 _addTorrentUrlToServer__callback Object
controller_actions.js:309 _getSession valid Object
controller_actions.js:350 _checkDaemonConnection Object
controller_actions.js:364 _checkDaemonConnection__callback Object Object
controller_actions.js:636 _getServerConfig Object
controller_actions.js:653 _getServerConfig__callback Object
controller_actions.js:270 _getDomainCookies for horrorcharnel.org
controller_actions.js:291 _getDomainCookies__callback horrorcharnel.org uid=7574;pass=d6123ffa07e90a31e5442d1ca73570cc;hashv=b94cbcbb740428a8d1d4b621a56d578d
controller_actions.js:912 _addTorrentUrlToServer core.add_torrent_url Array(3)
background.min.js:6 _addTorrentUrlToServer__callback Object
background.min.js:6 _getSession valid Object
background.min.js:6 _checkDaemonConnection Object
background.min.js:6 _checkDaemonConnection__callback Object Object
background.min.js:6 _getServerConfig Object
background.min.js:6 _getServerConfig__callback Object
background.min.js:6 _getDomainCookies for horrorcharnel.org
background.min.js:6 _getDomainCookies__callback horrorcharnel.org uid=7574;pass=d6123ffa07e90a31e5442d1ca73570cc;hashv=b94cbcbb740428a8d1d4b621a56d578d
background.min.js:6 _addTorrentUrlToServer core.add_torrent_url Array(3)
background.min.js:6 _addTorrentUrlToServer__callback Object
background.min.js:6 _getSession valid Object
background.min.js:6 _checkDaemonConnection Object
background.min.js:6 _checkDaemonConnection__callback Object Object
background.min.js:6 _getServerConfig Object
background.min.js:6 _getServerConfig__callback Object
background.min.js:6 _getDomainCookies for horrorcharnel.org
background.min.js:6 _getDomainCookies__callback horrorcharnel.org uid=7574;pass=d6123ffa07e90a31e5442d1ca73570cc;hashv=b94cbcbb740428a8d1d4b621a56d578d
background.min.js:6 _addTorrentUrlToServer core.add_torrent_url Array(3)
background.min.js:6 _addTorrentUrlToServer__callback Object
background.min.js:6 _getSession valid Object
background.min.js:6 _checkDaemonConnection Object
background.min.js:6 _checkDaemonConnection__callback Object Object
background.min.js:6 _getServerConfig Object
background.min.js:6 _getServerConfig__callback Object
background.min.js:6 _getDomainCookies for nebulance.io
background.min.js:6 _getDomainCookies__callback nebulance.io session=RFdHrX6Mn%2B6eyJO1v1na1sBPXXOJF3bDYPI9WCs0SBFhVgUhn57GRHy6awKvetuDDLWQCZAho%2BkgEb6CR9kFVSkDPx3MtAaxxQKZwgGmEYW50d13d8ghJ%2BPpOx51oZo7rmJw06C9IAWN3%2BMmSeUgDA%3D%3D;searchPanelState=expanded
background.min.js:6 _addTorrentUrlToServer core.add_torrent_url Array(3)
background.min.js:6 _addTorrentUrlToServer__callback Object
controller_actions.js:309 _getSession valid Object {id: "-16990", result: true, error: null}
controller_actions.js:350 _checkDaemonConnection Object {status: "Connected", port: 49111, ip: "127.0.0.1", host_id: "f12e372e1fd01d27a0537f09ca9aed046f7c170f", version: "1.3.15"}
controller_actions.js:364 _checkDaemonConnection__callback Object {id: "-16991", result: true, error: null} Object {status: "Connected", port: 49111, ip: "127.0.0.1", host_id: "f12e372e1fd01d27a0537f09ca9aed046f7c170f", version: "1.3.15"}
controller_actions.js:636 _getServerConfig Object {status: "Connected", port: 49111, ip: "127.0.0.1", host_id: "f12e372e1fd01d27a0537f09ca9aed046f7c170f", version: "1.3.15"}
controller_actions.js:653 _getServerConfig__callback Object {add_paused: false, move_completed_path: "/home/octophetus/files/Torrents", download_location: "/home/octophetus/files/Torrents", move_completed: false}
controller_actions.js:270 _getDomainCookies for horrorcharnel.org
controller_actions.js:291 _getDomainCookies__callback horrorcharnel.org uid=7574;pass=d6123ffa07e90a31e5442d1ca73570cc;hashv=b94cbcbb740428a8d1d4b621a56d578d
controller_actions.js:912 _addTorrentUrlToServer core.add_torrent_url (3) ["https://horrorcharnel.org/download.php?torrent=2742", Object, Object]
controller_actions.js:920 _addTorrentUrlToServer__callback Object {id: "-17004.0", result: null, error: null}

**Comment by sbussetti** [comment] 2018-03-27 12:12
So far confirmed your issue on MyAnonaMouse -- thanks for the detailed report.  I'll work on a fix.

**Comment by sbussetti** [comment] 2018-10-20 18:35
MyAnonaMouse:  Fixed in 0.72.0
Sceneaccess.eu:  Site appears to be down
Horror Charnel:  If you are adding the link directly to Deluge, and it still doesn't work, the problem is the link you're getting, not this extension.

**Closed by sbussetti** 2018-10-20 18:35 UTC
Labels: Bug, Site Compatibility
